'use client'
import { useEffect } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Gabarito, Noto_Sans, Ubuntu_Mono, Outfit} from "next/font/google";
import "./globals.css";
import { Navbar } from "components/navbar";
import { useThemeStore } from "hooks/useThemeStore";







const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const gabarito = Gabarito({
  variable: "--font-gabarito-latin",
  subsets: ["latin"],
});
const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});
const ubuntuMono = Ubuntu_Mono({
  variable: "--font-ubuntu-mono", 
    weight: ["400", "700"], // 👈 ADD THIS LINE
  subsets: ['latin']
})
const outfit = Outfit({
  variable: "--font-outfit", 
  subsets: ['latin']
})


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const {mode} = useThemeStore();
    useEffect(() => {
    // Apply/remove the dark class based on Zustand state
    if (typeof window !== "undefined") {
      console.log(document.documentElement)
      document.documentElement.classList.toggle("dark", mode === "dark");
    }
  }, [mode]);

  // console.log(mode)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gabarito.variable} ${notoSans.variable} ${ubuntuMono.variable} ${outfit.variable} bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100 antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
